from typing import Protocol

from app.modules.users.domain.entities import User

# Puertos de dominio que definen la interfaz del repo
class UserRepository(Protocol):
    def create(self, user: User) -> User: ...

    def get_by_id(self, user_id: int) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def get_by_username(self, username: str) -> User | None: ...

    def list_users(self, limit: int, offset: int) -> list[User]: ...

    def update(self, user: User) -> User: ...

    def delete(self, user_id: int) -> None: ...
